CREATE TABLE IF NOT EXISTS Daily_Activities
(
 id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   
 date           TIMESTAMPTZ DEFAULT now() NOT NULL,
 medicine       text NOT NULL,
 hours slept    integer NOT NULL,
 food           text NOT NULL,
 sugar intake   integer NOT NULL,
 rate focus     integer NOT NULL,
 rate happiness integer NOT NULL,
 rate energy    integer NOT NULL,
 User id        integer NOT NULL,
 CONSTRAINT "FK_49" FOREIGN KEY ( "User id" ) REFERENCES "Users" ( "User id" )
);

CREATE INDEX "fkIdx_49" ON "Daily Activities"
(
 "User id"
);