CREATE TABLE IF NOT EXISTS Daily_Activities
(
 id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   
 date           TIMESTAMPTZ DEFAULT now() NOT NULL,
 medicine       text NOT NULL,
 hours_slept    integer NOT NULL,
 food           text NOT NULL,
 sugar_intake   integer NOT NULL,
 rate_focus     integer NOT NULL,
 rate_happiness integer NOT NULL,
 rate_energy    integer NOT NULL,
 user_id        integer NOT NULL,
 CONSTRAINT "FK_49" FOREIGN KEY ( "user_id" ) REFERENCES "users" ( "user_id" )
);

CREATE INDEX "fkIdx_49" ON "daily_activities"
(
 "user_id"
);