CREATE TABLE IF NOT EXISTS Journal_Entry
(
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
date TIMESTAMPTZ DEFAULT now() NOT NULL,
 title   text NOT NULL,
 content text NOT NULL,
 mood    text NOT NULL,
 User id integer NOT NULL,
 CONSTRAINT "FK_38" FOREIGN KEY ( "User id" ) REFERENCES "Users" ( "User id" )
);

CREATE INDEX "fkIdx_38" ON "Journal Entry"
(
 "User id"
);

