CREATE TABLE IF NOT EXISTS Journal_Entry
(
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
date TIMESTAMPTZ DEFAULT now() NOT NULL,
 title   text NOT NULL,
 content text NOT NULL,
 mood    text NOT NULL,
 user_id integer NOT NULL,
 CONSTRAINT "FK_38" FOREIGN KEY ( "user_id" ) REFERENCES "users" ( "user_id" )
);

CREATE INDEX "fkIdx_38" ON "journal_entry"
(
 "user_id"
);

